// @vitest-environment jsdom
import { beforeEach, afterEach, describe, expect, it, vi } from 'vitest'
import { readProjectInput, readProject, readRoadmap, readProjectStore, createFallbackRoadmap, PROJECT_STORAGE_KEY, type ProjectInput } from '../../shared/longTermProjectSchema.mjs'
import { createProject, saveProject, loadProjects, projectId, generateProjectRoadmap, reorder } from './longTermProjects'
import { exportBackup, parseBackup, replaceLocalData } from './localBackup'
import { initialGamificationState } from '../types/gamification'
const input:ProjectInput={title:'Japanisch lernen',goal:'Japanisch im Alltag verwenden',startingLevel:{type:'beginner'},duration:{type:'fixed-days',days:30},weeklyMinutes:120,daysPerWeek:null,learningContext:{}}
const make=(changes:Partial<ProjectInput>={})=>{const i={...input,...changes};return createProject(i,createFallbackRoadmap(i,projectId))}
beforeEach(()=>localStorage.clear())
afterEach(()=>vi.useRealTimers())
describe('Projektmodell und konservative Eingaben',()=>{
 it('erstellt stabile lokale IDs und getrennte Daten',()=>{const p=make();expect(readProject(p)).toEqual(p);expect(p.id).toMatch(/^project-/);expect(new Set(p.roadmap.phases.flatMap(p=>[p.id,...p.milestones.map(m=>m.id)])).size).toBe(p.roadmap.phases.length*2)})
 it.each(['beginner','basic','advanced'] as const)('Vorwissen %s ohne Pflichttext',type=>expect(make({startingLevel:{type}}).startingLevel.type).toBe(type))
 it('eigene Ausgangslage und Vorwissen',()=>{expect(make({startingLevel:{type:'custom',description:'Hiragana',priorKnowledge:'100 Wörter'}}).startingLevel.description).toBe('Hiragana');expect(()=>make({startingLevel:{type:'custom',description:''}})).toThrow();expect(()=>make({startingLevel:{type:'custom',description:'x'.repeat(301)}})).toThrow();expect(()=>make({startingLevel:{type:'basic',priorKnowledge:'x'.repeat(401)}})).toThrow()})
 it.each([10,30,100,300])('%i Tage erzeugen kompakte Roadmap',days=>{const p=make({duration:{type:'fixed-days',days}});expect(p.duration).toEqual({type:'fixed-days',days});expect(p.roadmap.phases.length).toBeLessThanOrEqual(5);expect(p.roadmap.phases.reduce((n,p)=>n+(p.expectedDuration?.value ?? 0),0)).toBe(days);expect(JSON.stringify(p)).not.toContain('daily')})
 it('eigenes Datum und abgelaufene Projekte bleiben beim Reload valide',()=>{vi.useFakeTimers();vi.setSystemTime(new Date('2026-10-07T12:00:00Z'));const p=make({duration:{type:'date',targetDate:'2026-12-31'}});saveProject(p);vi.setSystemTime(new Date('2027-01-01'));expect(loadProjects().projects[0].id).toBe(p.id);expect(()=>readProjectInput({...input,duration:{type:'date',targetDate:'2026-02-30'}})).toThrow();expect(()=>readProjectInput({...input,duration:{type:'date',targetDate:'2026-10-06'}})).toThrow();expect(()=>readProjectInput({...input,duration:{type:'date',targetDate:'2040-01-01'}})).toThrow()})
 it('open-ended ist rollierend ohne 100%-Versprechen',()=>{const p=make({duration:{type:'open-ended'}});expect(p.roadmap.summary).toContain('Rollierende');expect(JSON.stringify(p)).not.toMatch(/100%|progress|percentage/)})
 it.each([60,120,300,600,155,30,4200])('Wochenzeit %i Minuten',weeklyMinutes=>expect(make({weeklyMinutes}).weeklyMinutes).toBe(weeklyMinutes))
 it.each([1,2,3,4,5,6,7])('%i Lerntage sind optionales Planungsfeld',daysPerWeek=>expect(make({daysPerWeek}).daysPerWeek).toBe(daysPerWeek))
 it.each([{weeklyMinutes:29},{weeklyMinutes:4201},{weeklyMinutes:1.5},{daysPerWeek:0},{daysPerWeek:8},{duration:{type:'fixed-days',days:-10}},{duration:{type:'fixed-days',days:0}}])('ungültige Zeit %j',changes=>expect(()=>readProjectInput({...input,...changes})).toThrow())
 it('verwendet den vorhandenen Lernkontext',()=>{const learningContext={environment:'private' as const,purpose:'interest' as const,materials:['other' as const],materialsDetails:'Eigene Karten'};expect(make({learningContext}).learningContext).toEqual(learningContext);expect(()=>make({learningContext:{materials:['none','book']}})).toThrow()})
})
describe('striktes versioniertes Roadmap-Schema',()=>{
 it('akzeptiert genau acht Phasen mit acht Meilensteinen',()=>{const p=make();const phase=p.roadmap.phases[0];const r={...p.roadmap,phases:Array.from({length:8},(_,i)=>({...phase,id:'p'+i,order:i,milestones:Array.from({length:8},(_,j)=>({id:'m'+i+'-'+j,title:'Begrenzte Etappe',order:j}))}))};expect(readRoadmap(r).phases).toHaveLength(8);expect(()=>readRoadmap({...r,phases:[...r.phases,{...phase,id:'extra',order:8}]})).toThrow();expect(()=>readRoadmap({...r,phases:[{...r.phases[0],milestones:[...r.phases[0].milestones,{id:'extra',title:'Extra',order:8}]}]})).toThrow()})
 it('verwirft Tageslisten, fremde Felder, doppelte IDs, Reihenfolge und Version',()=>{const r=make().roadmap;expect(()=>readRoadmap({...r,days:Array.from({length:300})})).toThrow();expect(()=>readRoadmap({...r,version:2})).toThrow();expect(()=>readRoadmap({...r,phases:[{...r.phases[0],order:1}]})).toThrow();expect(()=>readRoadmap({...r,phases:[{...r.phases[0],milestones:[{...r.phases[0].milestones[0],id:r.phases[0].id}]}]})).toThrow()})
 it('Fallback berücksichtigt Vorwissen, Zeit und Ziel ohne Fachdetails zu erfinden',()=>{const a=make(),b=make({startingLevel:{type:'advanced'},duration:{type:'open-ended'},weeklyMinutes:60});expect(a.roadmap.summary).toContain(input.goal);expect(b.roadmap.summary).toContain('60 Minuten');expect(a.roadmap.phases[0].description).not.toEqual(b.roadmap.phases[0].description);expect(a.roadmap.summary).not.toContain('Hiragana')})
 it('Netzwerk-, HTTP-, JSON- und Schemafehler erzeugen Fallback ohne Retry',async()=>{for(const response of [()=>Promise.reject(new Error('secret')),()=>Promise.resolve(new Response('{}',{status:503})),()=>Promise.resolve(new Response('bad')),()=>Promise.resolve(new Response(JSON.stringify({source:'groq',roadmap:{version:1,phases:[]}})))]) {const fetcher=vi.fn(response);const result=await generateProjectRoadmap(input,fetcher);expect(readRoadmap(result.roadmap)).toEqual(result.roadmap);expect(result.notice).toContain('lokaler');expect(result.notice).not.toContain('secret');expect(fetcher).toHaveBeenCalledTimes(1)}})
 it('valide KI-Roadmap erhält lokal generierte IDs',async()=>{const roadmap=make().roadmap;const result=await generateProjectRoadmap(input,vi.fn().mockResolvedValue(new Response(JSON.stringify({source:'groq',roadmap}))));expect(result.roadmap.phases[0].id).not.toBe(roadmap.phases[0].id);expect(result.notice).toContain('KI-Roadmap')})
 it('Client-Timeout funktioniert auch bei hängendem Fetch',async()=>{vi.useFakeTimers();const fetcher=vi.fn(()=>new Promise<Response>(()=>{}));const promise=generateProjectRoadmap(input,fetcher);await vi.advanceTimersByTimeAsync(25000);expect((await promise).notice).toContain('lokaler');expect(fetcher).toHaveBeenCalledTimes(1)})
})
describe('Bearbeiten, Storage und Backup',()=>{
 it('bearbeitet Titel, Phasen und Meilensteine, fügt hinzu, löscht und ordnet stabil um',()=>{const p=make(),phase=p.roadmap.phases[0];phase.title='Mein Einstieg';phase.milestones.push({id:projectId(),title:'Eigener Meilenstein',order:1});phase.milestones=reorder(phase.milestones,1,-1);expect(phase.milestones[0].title).toBe('Eigener Meilenstein');phase.milestones=phase.milestones.slice(0,1);p.roadmap.phases=reorder(p.roadmap.phases,1,-1);p.title='Mein Japanisch';saveProject(p);expect(loadProjects().projects[0]).toEqual(p);expect(loadProjects().projects[0].roadmap.phases[1].id).toBe(phase.id)})
 it.each(['paused','archived','completed'] as const)('Status %s ohne Vergütung, Fokuszeit oder Prestigeänderung',status=>{localStorage.setItem('mission.gamification.v1',JSON.stringify(initialGamificationState));localStorage.setItem('mission.statistics.v1','existing statistics');localStorage.setItem('mission.saved-mission.v1','existing mission');const p=make();saveProject({...p,status});expect(loadProjects().projects[0].status).toBe(status);expect(localStorage.getItem('mission.gamification.v1')).toBe(JSON.stringify(initialGamificationState));expect(localStorage.getItem('mission.statistics.v1')).toBe('existing statistics');expect(localStorage.getItem('mission.saved-mission.v1')).toBe('existing mission')})
 it('Reload behält IDs und Notizen',()=>{const p={...make(),manualNotes:'Nächste Fragen'};saveProject(p);expect(loadProjects().projects[0]).toEqual(p)})
 it('isoliert beschädigte Einzelprojekte und verhindert Überschreiben beschädigter Wurzeln',()=>{const p=make();localStorage.setItem(PROJECT_STORAGE_KEY,JSON.stringify({version:1,projects:[p,{broken:true}]}));expect(loadProjects().projects).toEqual([p]);expect(loadProjects().rejected).toBe(1);expect(()=>readProjectStore(JSON.parse(localStorage.getItem(PROJECT_STORAGE_KEY)!))).toThrow();localStorage.setItem(PROJECT_STORAGE_KEY,'bad');expect(loadProjects().damaged).toBe(true);expect(()=>saveProject(p)).toThrow();expect(localStorage.getItem(PROJECT_STORAGE_KEY)).toBe('bad')})
 it('maximal 50 Projekte und Updates bei erreichtem Limit',()=>{const projects=Array.from({length:50},()=>make());localStorage.setItem(PROJECT_STORAGE_KEY,JSON.stringify({version:1,projects}));expect(()=>saveProject(make())).toThrow(/50/);expect(saveProject({...projects[0],title:'Aktualisiert'})).toHaveLength(50)})
 it('Backup v1 exportiert und importiert Projekte ohne neue Belohnung',()=>{const p=make();saveProject(p);localStorage.setItem('mission.gamification.v1',JSON.stringify(initialGamificationState));const backup=parseBackup(exportBackup());expect(backup.version).toBe(1);expect(backup.data['mission.projects.v1']).toEqual({version:1,projects:[p]});localStorage.clear();replaceLocalData(backup,true);expect(loadProjects().projects[0]).toEqual(p);expect(JSON.parse(localStorage.getItem('mission.gamification.v1')!)).toEqual(initialGamificationState)})
 it('alte Backups ohne Projekte bleiben lesbar und Ersetzen entfernt alte Projekte',()=>{saveProject(make());const old=parseBackup(JSON.stringify({format:'mission-backup',version:1,exportedAt:new Date().toISOString(),data:{}}));replaceLocalData(old,true);expect(loadProjects().projects).toEqual([])})
 it('Backup verwirft beschädigte Projekte und versteckte AI-Daten atomar',()=>{const p=make(),old=JSON.stringify({version:1,projects:[p]});localStorage.setItem(PROJECT_STORAGE_KEY,old);for(const value of [{...p,aiResponse:'secret'},{...p,roadmap:{...p.roadmap,phases:[]}}]) {expect(()=>replaceLocalData({format:'mission-backup',version:1,exportedAt:new Date().toISOString(),data:{'mission.projects.v1':{version:1,projects:[value]}}},true)).toThrow();expect(localStorage.getItem(PROJECT_STORAGE_KEY)).toBe(old)}})
})

it('maximale gültige Texte bleiben im Fallback innerhalb des Schemas',()=>{const p=make({title:'T'.repeat(90),goal:'Z'.repeat(280),startingLevel:{type:'custom',description:'D'.repeat(300),priorKnowledge:'V'.repeat(400)}});expect(p.roadmap.summary.length).toBeLessThanOrEqual(400);expect(readProject(p)).toEqual(p)})
