// @vitest-environment jsdom
import { beforeEach, afterEach, expect, it, vi } from 'vitest'
import { createProject, projectId, saveProject, loadProjects } from './longTermProjects'
import { createFallbackRoadmap, PROJECT_STORAGE_KEY, readProject, type ProjectInput } from '../../shared/longTermProjectSchema.mjs'
import { emptyLearningState, readLearningState } from '../../shared/projectLearningState.mjs'
import { localReview, readReviewProposal, readReviewInput } from '../../shared/projectReviewSchema.mjs'
import { captureSessionReview, createReviewTicket, applyProjectReview, saveReviewDraft, generateSessionReview, reconcileAppliedReviews, MISSION_STATE_KEY } from './projectReview'
import { buildProjectMissionContext } from '../../shared/projectMissionContext.mjs'
import { generateRuleBasedLearningPlan } from './ruleBasedLearningPlan'
import { normalizeHistory, type SessionHistoryEntry } from './learningHistory'
import { exportBackup, parseBackup, replaceLocalData } from './localBackup'
const input:ProjectInput={title:'Japanisch',goal:'Japanisch lernen',startingLevel:{type:'basic',priorKnowledge:'Hiragana'},duration:{type:'open-ended'},weeklyMinutes:120,daysPerWeek:3,learningContext:{materials:['none']}}
function seed(){const project=createProject(input,createFallbackRoadmap(input,projectId));saveProject(project);const phase=project.roadmap.phases[0],sourceProject={projectId:project.id,phaseId:phase.id,milestoneIds:[phase.milestones[0].id]};const form={goal:input.goal,timeBudgetMinutes:30,energyLevel:'low' as const,learningBlocker:'starting' as const};const plan={...generateRuleBasedLearningPlan(form),sourceProject};plan.steps[0].done=true;const entry:SessionHistoryEntry={id:'session-1',goal:input.goal,startedAt:'2026-10-07T10:00:00.000Z',endedAt:'2026-10-07T10:30:00.000Z',status:'completed',focusSeconds:1800,plannedSeconds:1800,timeMode:'manual',completedSteps:1,totalSteps:plan.steps.length,sourceProject};entry.projectReview=captureSessionReview(entry,plan);localStorage.setItem(MISSION_STATE_KEY,JSON.stringify({form,mission:plan,remainingSeconds:0,elapsedSeconds:0,history:[entry],activeSession:null,focusBlocks:null}));const ticket=createReviewTicket(entry);return {project,phase,plan,entry,ticket,draft:localReview(ticket.input)}}
beforeEach(()=>localStorage.clear())
afterEach(()=>{vi.useRealTimers();vi.restoreAllMocks()})
it('Projektabschluss erfasst nur Session-Schritte und macht keine Mutation',()=>{const {project,entry,ticket,draft}=seed();expect(entry.projectReview?.status).toBe('pending');expect(draft.suggestedKnown).toEqual([]);expect(ticket.input.steps[0].done).toBe(true);expect(loadProjects().projects[0]).toEqual(project);expect(JSON.stringify(ticket.input)).not.toMatch(/coins|prestige|history|orbs|level/i)})
it('normale Mission erzeugt keinen Review',()=>{const {entry,plan}=seed();expect(captureSessionReview({...entry,sourceProject:undefined},plan)).toBeUndefined()})
it.each(['missing','archived','phase','milestone','damaged'] as const)('%s Projektzustand verhindert Apply',kind=>{const {project,ticket,draft}=seed();if(kind==='missing')localStorage.setItem(PROJECT_STORAGE_KEY,JSON.stringify({version:1,projects:[]}));else if(kind==='damaged')localStorage.setItem(PROJECT_STORAGE_KEY,'broken');else saveProject({...project,...(kind==='archived'?{status:'archived' as const}:{}),roadmap:kind==='phase'?{...project.roadmap,phases:project.roadmap.phases.map(p=>({...p,id:projectId()}))}:kind==='milestone'?{...project.roadmap,phases:project.roadmap.phases.map(p=>({...p,milestones:p.milestones.map(m=>({...m,id:projectId()}))}))}:project.roadmap});expect(()=>applyProjectReview(ticket,draft,true)).toThrow()})
it('Bekannt/In Arbeit/Unsicher und Notiz werden nur bestätigt gespeichert',()=>{const {ticket,draft,project}=seed();const proposal={...draft,sessionSummary:'Lesen geübt',suggestedKnown:['Hiragana'],suggestedInProgress:['Sätze'],suggestedWeak:['Partikel'],nextSessionNote:'Partikel mit kleinen Beispielen üben'};expect(loadProjects().projects[0].learningState).toBeUndefined();const result=applyProjectReview(ticket,proposal,true);expect(result.project.learningState).toMatchObject({known:['Hiragana'],inProgress:['Sätze'],weak:['Partikel'],nextSessionNote:proposal.nextSessionNote});expect(result.history[0].sourceProject).toEqual({projectId:project.id,phaseId:ticket.input.phase.id,milestoneIds:ticket.input.milestoneIds});expect(result.history[0].projectReview?.status).toBe('applied')})
it.each([true,false])('Meilenstein-Abschluss braucht Nutzerentscheidung %s',confirm=>{const {ticket,draft,phase}=seed();draft.milestoneSuggestions[0].suggestion=confirm?'mark-completed':'keep-open';expect(loadProjects().projects[0].roadmap.phases[0].milestones[0].status).not.toBe('completed');applyProjectReview(ticket,draft,true);expect(loadProjects().projects[0].roadmap.phases[0].milestones[0].status==='completed').toBe(confirm);expect(loadProjects().projects[0].roadmap.phases[0].id).toBe(phase.id)})
it('Skip und Reload erhalten bearbeiteten Entwurf; später genau einmal übernehmen',()=>{const {ticket,draft}=seed();draft.suggestedInProgress=['Lesen'];saveReviewDraft(ticket.sessionId,draft,'pending',true);saveReviewDraft(ticket.sessionId,undefined,'skipped',true);const entry=normalizeHistory(JSON.parse(localStorage.getItem(MISSION_STATE_KEY)!).history)[0];expect(entry.projectReview?.draft?.suggestedInProgress).toEqual(['Lesen']);const reloaded=createReviewTicket(entry);applyProjectReview(reloaded,draft,true);expect(()=>applyProjectReview(reloaded,draft,true)).toThrow();expect(()=>createReviewTicket(normalizeHistory(JSON.parse(localStorage.getItem(MISSION_STATE_KEY)!).history)[0])).toThrow();expect(loadProjects().projects[0].learningState?.recentProgress).toHaveLength(1)})
it('Projektbeleg verhindert Apply auch bei unterbrochenem History-Schreiben',()=>{const {entry,ticket,draft}=seed();applyProjectReview(ticket,draft,true);localStorage.setItem(MISSION_STATE_KEY,JSON.stringify({...JSON.parse(localStorage.getItem(MISSION_STATE_KEY)!),history:[entry]}));expect(()=>applyProjectReview(ticket,draft,true)).toThrow();expect(reconcileAppliedReviews([entry],loadProjects().projects)[0].projectReview?.status).toBe('applied')})
it('fehlender Web-Lock verhindert Draft und Apply ohne Schreibzugriff',()=>{const {ticket,draft}=seed(),before={...localStorage};expect(()=>applyProjectReview(ticket,draft,false)).toThrow(/Schreibsperre/);expect(()=>saveReviewDraft(ticket.sessionId,draft,'pending',false)).toThrow();expect({...localStorage}).toEqual(before)})
it('zweiter Tab muss Sessionstatus frisch prüfen',()=>{const {ticket,draft}=seed();const second=structuredClone(ticket);applyProjectReview(ticket,draft,true);expect(()=>applyProjectReview(second,draft,true)).toThrow()})
it('geänderte Phase verhindert veraltete Übernahme',()=>{const {ticket,draft,project}=seed();project.roadmap.phases[0].title='Neue Phase';saveProject(project);expect(()=>applyProjectReview(ticket,draft,true)).toThrow(/geändert/)})
it('Review verändert keine Coins, Fokuszeit oder Prestige',()=>{const {ticket,draft}=seed();for(const key of ['mission.gamification.v1','mission.statistics.v1'])localStorage.setItem(key,'immutable-reward-data');applyProjectReview(ticket,draft,true);expect(localStorage.getItem('mission.gamification.v1')).toBe('immutable-reward-data');expect(localStorage.getItem('mission.statistics.v1')).toBe('immutable-reward-data')})
it('alte Projekte und Backups ohne Lernstand bleiben gültig',()=>{const {project}=seed();expect(readProject(project).learningState).toBeUndefined();const backup=parseBackup(exportBackup());replaceLocalData(backup,true);expect(loadProjects().projects[0].learningState).toBeUndefined()})
it('Backup erhält sourceProject, Lernstand und Applied-Beleg',()=>{const {ticket,draft}=seed();applyProjectReview(ticket,{...draft,suggestedKnown:['Hiragana']},true);const backup=parseBackup(exportBackup());localStorage.clear();replaceLocalData(backup,true);const entry=normalizeHistory(JSON.parse(localStorage.getItem(MISSION_STATE_KEY)!).history)[0];expect(entry.sourceProject?.projectId).toBe(ticket.projectId);expect(entry.projectReview?.status).toBe('applied');expect(loadProjects().projects[0].learningState?.known).toEqual(['Hiragana']);expect(()=>applyProjectReview(ticket,draft,true)).toThrow()})
it('beschädigter Lernstand und Review im Backup werden abgelehnt',()=>{const {project}=seed();expect(()=>readProject({...project,learningState:{...emptyLearningState(),known:Array(31).fill('A')}})).toThrow();const backup=JSON.parse(exportBackup());backup.data[MISSION_STATE_KEY].history[0].projectReview.draft={sessionSummary:'x'};expect(()=>parseBackup(JSON.stringify(backup))).toThrow()})
it.each(['known','inProgress','weak'] as const)('%s maximal 30 Themen mit 120 Zeichen',key=>{const state={...emptyLearningState(),[key]:Array.from({length:30},(_,i)=>'Thema '+i)};expect(readLearningState(state)[key]).toHaveLength(30);expect(()=>readLearningState({...state,[key]:[...state[key],'31']})).toThrow();expect(()=>readLearningState({...state,[key]:['x'.repeat(121)]})).toThrow()})
it('recentProgress begrenzt auf zehn; nächste Mission enthält höchstens drei',()=>{const {project,ticket,draft}=seed();const state={...emptyLearningState(),recentProgress:Array.from({length:10},(_,i)=>({id:'r'+i,sessionId:'old'+i,createdAt:'2026-10-06T10:00:00.000Z',summary:'Fortschritt '+i}))};saveProject({...project,learningState:state});const entry=normalizeHistory(JSON.parse(localStorage.getItem(MISSION_STATE_KEY)!).history)[0];const result=applyProjectReview(createReviewTicket(entry),draft,true);expect(result.project.learningState?.recentProgress).toHaveLength(10);expect(buildProjectMissionContext(result.project).learningState?.recentProgress).toHaveLength(3);expect(()=>readLearningState({...state,recentProgress:[...state.recentProgress,state.recentProgress[0]]})).toThrow();expect(ticket.input.learningState).toBeUndefined()})
it('nächste Mission berücksichtigt bestätigte Kategorien und bleibt unter 6 KiB',()=>{const {project}=seed();const state={...emptyLearningState(),known:Array.from({length:30},(_,i)=>('Bekannt '+i+' ').padEnd(120,'a')),inProgress:Array.from({length:30},(_,i)=>('Arbeit '+i+' ').padEnd(120,'b')),weak:Array.from({length:30},(_,i)=>('Unsicher '+i+' ').padEnd(120,'c')),recentProgress:Array.from({length:10},(_,i)=>({id:'r'+i,sessionId:'s'+i,createdAt:'2026-10-06T10:00:00.000Z',summary:'R'.repeat(240)}))};const context=buildProjectMissionContext({...project,learningState:state});expect(context.learningState?.known.length).toBeLessThanOrEqual(5);expect(context.learningState?.inProgress.length).toBeLessThanOrEqual(5);expect(context.learningState?.weak.length).toBeLessThanOrEqual(5);expect(context.learningState?.recentProgress.length).toBeLessThanOrEqual(3);expect(new TextEncoder().encode(JSON.stringify(context)).length).toBeLessThanOrEqual(6144);expect(context).not.toHaveProperty('history')})
it('unbekannte Meilenstein-IDs und zu große Vorschläge abgelehnt',()=>{const {ticket,draft}=seed();expect(()=>readReviewProposal({...draft,milestoneSuggestions:[{milestoneId:'unknown',suggestion:'mark-completed',reason:'x'}]},ticket.input.milestoneIds)).toThrow();expect(()=>readReviewProposal({...draft,suggestedKnown:['a','b','c','d']},ticket.input.milestoneIds)).toThrow();expect(()=>readReviewInput({...ticket.input,history:[]})).toThrow()})
it('valide KI-Ausgabe wird als Vorschlag angenommen ohne Projektmutation',async()=>{const {ticket,draft,project}=seed();const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({source:'groq',review:{...draft,suggestedInProgress:['Lesen']}})));const result=await generateSessionReview(ticket.input,fetcher);expect(result.proposal.suggestedInProgress).toEqual(['Lesen']);expect(loadProjects().projects[0]).toEqual(project);expect(fetcher).toHaveBeenCalledTimes(1)})
it.each(['offline','429','invalid'])('%s bietet lokalen Review ohne Retries',async kind=>{const {ticket}=seed();const fetcher=kind==='offline'?vi.fn().mockRejectedValue(new TypeError('offline')):vi.fn().mockResolvedValue(new Response(kind==='invalid'?'{}':'rate limited',{status:kind==='429'?429:200}));const result=await generateSessionReview(ticket.input,fetcher);expect(result.proposal.suggestedKnown).toEqual([]);expect(result.notice).toContain('lokale');expect(fetcher).toHaveBeenCalledTimes(1)})
it('Timeout bietet lokalen Review und bricht Request ab',async()=>{vi.useFakeTimers();const {ticket}=seed();let signal:AbortSignal|undefined;const fetcher=vi.fn().mockImplementation((_:unknown,options:RequestInit)=>{signal=options.signal as AbortSignal;return new Promise(()=>{})});const promise=generateSessionReview(ticket.input,fetcher);await vi.advanceTimersByTimeAsync(25000);expect((await promise).proposal.suggestedKnown).toEqual([]);expect(signal?.aborted).toBe(true);expect(fetcher).toHaveBeenCalledTimes(1)})

it('nächster Kontext enthält ursprüngliches Vorwissen und bestätigte Kategorien',()=>{const {project}=seed();const learningState={...emptyLearningState(),known:['Hiragana'],inProgress:['Sätze'],weak:['Partikel'],nextSessionNote:'Partikel üben'};const context=buildProjectMissionContext({...project,learningState});expect(context.startingLevel.priorKnowledge).toBe('Hiragana');expect(context.learningState).toMatchObject({known:['Hiragana'],inProgress:['Sätze'],weak:['Partikel'],nextSessionNote:'Partikel üben'});expect(context.duration.type).toBe('open-ended');expect(JSON.stringify(context)).not.toMatch(/percent|progressPercentage|history/);})
it('Client verwirft unbelegte neue KI-known-Behauptung',async()=>{const {ticket,draft}=seed();const result=await generateSessionReview(ticket.input,vi.fn().mockResolvedValue(new Response(JSON.stringify({source:'groq',review:{...draft,suggestedKnown:['Neues Thema beherrscht']}}))));expect(result.proposal.suggestedKnown).toEqual([]);expect(result.notice).toContain('lokale')})

it('große Unicode-Session bleibt lokal reviewbar, Promptkompression verändert keine History',()=>{const {project,entry,plan}=seed();plan.steps=Array.from({length:12},(_,i)=>({...plan.steps[0],id:'step-'+i,title:'漢'.repeat(90),description:'字'.repeat(200)}));entry.totalSteps=12;entry.projectReview=captureSessionReview(entry,plan);const state={...emptyLearningState(),known:Array.from({length:30},(_,i)=>(i+'漢'.repeat(120)).slice(0,120)),inProgress:Array.from({length:30},(_,i)=>(i+'字'.repeat(120)).slice(0,120)),weak:Array.from({length:30},(_,i)=>(i+'語'.repeat(120)).slice(0,120)),recentProgress:Array.from({length:10},(_,i)=>({id:'r'+i,sessionId:'old'+i,createdAt:'2026-10-06T10:00:00.000Z',summary:'話'.repeat(240)}))};saveProject({...project,learningState:state});const before=JSON.stringify(entry);const ticket=createReviewTicket(entry);expect(new TextEncoder().encode(JSON.stringify(ticket.input)).length).toBeLessThanOrEqual(12288);expect(localReview(ticket.input).sessionSummary.length).toBeLessThanOrEqual(240);expect(JSON.stringify(entry)).toBe(before);expect(new TextEncoder().encode(JSON.stringify(buildProjectMissionContext({...project,learningState:state}))).length).toBeLessThanOrEqual(6144)})
