// @vitest-environment jsdom
import { beforeEach, afterEach, describe, expect, it, vi } from 'vitest'
import { createProject, projectId, saveProject, loadProjects } from './longTermProjects'
import { projectMissionRequest, currentProjectContext, assertCurrentProjectContext } from './projectMission'
import { buildProjectMissionContext, readProjectMissionContext, MAX_PROJECT_CONTEXT_BYTES, unnecessaryKnownTopic } from '../../shared/projectMissionContext.mjs'
import { readRoadmap, PROJECT_STORAGE_KEY, type ProjectInput } from '../../shared/longTermProjectSchema.mjs'
import { generateLearningPlanWithStatus } from './learningPlanGenerator'
import { generateRuleBasedLearningPlan } from './ruleBasedLearningPlan'
import { validateLearningPlanResponse, validatePlanInput } from '../../shared/learningPlanSchema.mjs'
import { validateEditablePlan, applyPlanTiming } from './planEditor'
import { normalizeHistory, normalizeActiveSession, finishLearningSession } from './learningHistory'
import { initialGamificationState } from '../types/gamification'
import { exportBackup, parseBackup, replaceLocalData } from './localBackup'
const input:ProjectInput={title:'Java lernen',goal:'Java anwenden',startingLevel:{type:'basic',priorKnowledge:'Ich kenne Vererbung'},duration:{type:'open-ended'},weeklyMinutes:120,daysPerWeek:3,learningContext:{environment:'private',purpose:'interest',materials:['none']}}
function seed() {const p=createProject(input,readRoadmap({version:1,summary:'Roadmap für Java',phases:[{id:projectId(),title:'Grundlagen',description:'Begrenzter Einstieg',order:0,milestones:[{id:projectId(),title:'Vererbung',order:0},{id:projectId(),title:'Streams anwenden',order:1}]},{id:projectId(),title:'Anwendung',description:'Eigener Transfer',order:1,milestones:[{id:projectId(),title:'Kleines Java-Projekt',order:0}]}]}));saveProject(p);return p}
const session={timeBudgetMinutes:30,energyLevel:'medium' as const,learningBlocker:'starting' as const}
beforeEach(()=>localStorage.clear())
afterEach(()=>{vi.useRealTimers();vi.restoreAllMocks();vi.unstubAllGlobals()})
describe('Projekt→Session-Kontext',()=>{
 it('aktives Projekt mit aktueller Phase und relevantem unbekanntem Meilenstein',()=>{const p=seed(),r=projectMissionRequest(p.id,session);expect(r.projectContext?.phase.id).toBe(p.roadmap.phases[0].id);expect(r.projectContext?.phase.milestones[0].title).toBe('Streams anwenden');expect(r.learningContext).toEqual(p.learningContext);expect(r.projectContext?.startingLevel.priorKnowledge).toContain('Vererbung');expect(validatePlanInput(r)).toBe(true)})
 it.each(['paused','completed','archived'] as const)('%s blockiert Tagesmission',status=>{const p=seed();saveProject({...p,status});expect(()=>projectMissionRequest(p.id,session)).toThrow(/Reaktiviere/)})
 it('wählt erste offene Phase und migriert alte fehlende Statuswerte ohne ID-Wechsel',()=>{const p=seed();p.roadmap.phases[0].milestones=p.roadmap.phases[0].milestones.map(m=>({...m,status:'completed'}));saveProject(p);expect(currentProjectContext(p.id).phase.id).toBe(p.roadmap.phases[1].id);expect(loadProjects().projects[0].roadmap.phases[0].milestones[0].id).toBe(p.roadmap.phases[0].milestones[0].id)})
 it('alle Meilensteine erledigt erzeugt keine künstliche nächste Etappe',()=>{const p=seed();p.roadmap.phases.forEach(v=>v.milestones.forEach(m=>m.status='completed'));saveProject(p);expect(()=>currentProjectContext(p.id)).toThrow(/Alle Meilensteine/)})
 it('Löschung, Archivierung, geänderte Phase und beschädigter Storage während Anfrage blockieren Übernahme',()=>{for(const action of ['delete','archive','phase','broken']){localStorage.clear();const p=seed(),context=currentProjectContext(p.id);if(action==='delete')localStorage.removeItem(PROJECT_STORAGE_KEY);if(action==='archive')saveProject({...p,status:'archived'});if(action==='phase'){p.roadmap.phases[0].milestones[0].status='completed';saveProject(p)}if(action==='broken')localStorage.setItem(PROJECT_STORAGE_KEY,'bad');expect(()=>assertCurrentProjectContext(context)).toThrow()}})
 it('begrenzt Kontext auf eine Phase und drei Meilensteine ohne Historie, Notizen, Coins oder Prestige',()=>{const p=seed();p.manualNotes='PRIVATE_NOTES';p.roadmap.phases[0].milestones=Array.from({length:8},(_,i)=>({id:projectId(),title:'Etappe '+i,order:i}));const c=buildProjectMissionContext(p),raw=JSON.stringify(c);expect(c.phase.milestones).toHaveLength(3);expect(raw).not.toMatch(/PRIVATE_NOTES|history|coins|prestige|orb|totalFocus|phases/);expect(new TextEncoder().encode(raw).length).toBeLessThanOrEqual(MAX_PROJECT_CONTEXT_BYTES);expect(()=>readProjectMissionContext({...c,history:[]})).toThrow();expect(()=>readProjectMissionContext({...c,roadmapSummary:'x'.repeat(7000)})).toThrow();expect(()=>readProjectMissionContext({...c,phase:{...c.phase,id:''}})).toThrow()})
 it('komprimiert große Unicode-Freitexte deterministisch innerhalb des Bytelimits',()=>{const p=seed();p.title='界'.repeat(90);p.goal='界'.repeat(280);p.startingLevel={type:'custom',description:'界'.repeat(300),priorKnowledge:'界'.repeat(400)};p.learningContext={materials:['other'],materialsDetails:'界'.repeat(240)};p.roadmap.summary='界'.repeat(400);p.roadmap.phases[0].title='界'.repeat(90);p.roadmap.phases[0].description='界'.repeat(300);p.roadmap.phases[0].milestones=Array.from({length:8},(_,i)=>({id:projectId(),title:'界'.repeat(90),description:'界'.repeat(200),order:i}));const c=buildProjectMissionContext(p);expect(new TextEncoder().encode(JSON.stringify(c)).length).toBeLessThanOrEqual(MAX_PROJECT_CONTEXT_BYTES);expect(readProjectMissionContext(c)).toEqual(c)})
})
describe('normale Pläne, Fallback und Vorwissen',()=>{
 it.each([5,30,60])('%i Minuten bleiben exakt',timeBudgetMinutes=>{const p=seed(),r=projectMissionRequest(p.id,{...session,timeBudgetMinutes}),plan=generateRuleBasedLearningPlan(r);expect(plan.steps.reduce((n,s)=>n+s.minutes,0)).toBe(timeBudgetMinutes);expect(validateEditablePlan(plan)).toBeNull();expect(plan.sourceProject?.projectId).toBe(p.id);expect(JSON.stringify(plan)).not.toContain('projectContext')})
 it.each(['low','medium','high'] as const)('Energie %s sichtbar',energyLevel=>{const p=seed(),r=projectMissionRequest(p.id,{...session,energyLevel}),plan=generateRuleBasedLearningPlan(r);expect(plan.energyLevel).toBe(energyLevel);expect(JSON.stringify(plan.steps)).toContain(energyLevel==='low' ? 'kleiner' : energyLevel==='high' ? 'anspruchsvollere' : 'Tempo')})
 it.each(['starting','understanding','focus','time','other'] as const)('Blocker %s im Fallback',learningBlocker=>{const p=seed(),plan=generateRuleBasedLearningPlan(projectMissionRequest(p.id,{...session,learningBlocker,learningBlockerDetails:'Heute müde'}));expect(plan.learningBlocker).toBe(learningBlocker);expect(JSON.stringify(plan.steps)).toMatch(learningBlocker==='understanding' ? /unklar/ : learningBlocker==='focus' ? /Tabs/ : learningBlocker==='time' ? /wichtigste/ : /klein/)})
 it('Fallback plant bekannte Vererbung nicht neu und nennt Phase/Meilenstein auch ohne Materialien',()=>{const p=seed(),r=projectMissionRequest(p.id,session),plan=generateRuleBasedLearningPlan(r);expect(plan.steps.some(s=>s.title.includes('Vererbung'))).toBe(false);expect(plan.steps[0].description).toContain('Grundlagen');expect(plan.steps[0].description).toContain('Streams');expect(JSON.stringify(plan)).not.toMatch(/100%|Projekt.*abgeschlossen/);expect(plan.learningContext).toEqual(input.learningContext)})
 it('bekanntes Hauptziel ist ungültig, kurze gekennzeichnete Wiederholung zulässig',()=>{const p=seed(),r=projectMissionRequest(p.id,session);expect(unnecessaryKnownTopic([{title:'Vererbung lernen',kind:'learning',minutes:30}],r)).toBe(0);expect(unnecessaryKnownTopic([{title:'Wiederholung Vererbung',kind:'learning',minutes:3},{title:'Streams',kind:'practice',minutes:27}],r)).toBe(-1);expect(unnecessaryKnownTopic([{title:'Wiederholung Vererbung',kind:'learning',minutes:3},{title:'Abruf Vererbung',kind:'learning',minutes:3}],r)).toBe(0)})
 it('Fokusstrategie und Planeditor bleiben nutzbar, Referenz bleibt erhalten',()=>{const p=seed(),r=projectMissionRequest(p.id,{...session,focusStrategy:{mode:'pomodoro'}}),plan={...generateRuleBasedLearningPlan(r),focusStrategy:{mode:'pomodoro' as const},timeMode:'automatic' as const};plan.steps[0].title='Eigener Einstieg';plan.steps[0].minutes+=5;expect(validateEditablePlan(plan)).toBeNull();const changed=applyPlanTiming(plan,60);expect(changed.plan.sourceProject).toEqual(plan.sourceProject);expect(changed.plan.timeBudgetMinutes).toBe(35)})
 it.each([0,4,7,65])('AI-Zeit %i wird vor der Anfrage verworfen',timeBudgetMinutes=>{const p=seed();expect(()=>projectMissionRequest(p.id,{...session,timeBudgetMinutes})).toThrow()})
 it('alte normale Mission bleibt valide und ohne Projektbezug',()=>{const r={goal:'Java lernen',...session},plan=generateRuleBasedLearningPlan(r);expect(validateLearningPlanResponse({source:'mock',clarifyingQuestion:null,plan},r)).toBe(true);expect(plan.sourceProject).toBeUndefined()})
 it('Netzwerk, Offline, 429 und ungültige AI-Antwort verwenden sicheren bestehenden Fallback ohne Retry',async()=>{const p=seed(),r=projectMissionRequest(p.id,session);for(const response of [()=>Promise.reject(new Error('private')),()=>Promise.resolve(new Response(JSON.stringify({error:{category:'rate_limited'}}),{status:429,headers:{'retry-after':'10'}})),()=>Promise.resolve(new Response('bad')),()=>Promise.resolve(new Response('{}'))]){const fetchImpl=vi.fn(response);const result=await generateLearningPlanWithStatus(r,fetchImpl);expect(result.source).toBe('fallback');expect(result.plan.sourceProject?.projectId).toBe(p.id);expect(fetchImpl).toHaveBeenCalledTimes(1);expect(result.notice).not.toContain('private')}Object.defineProperty(navigator,'onLine',{configurable:true,value:false});const result=await generateLearningPlanWithStatus(r,vi.fn().mockRejectedValue(new TypeError('offline')));expect(result.notice).toContain('offline');Object.defineProperty(navigator,'onLine',{configurable:true,value:true})})
 it('Timeout ohne Retries',async()=>{vi.useFakeTimers();const p=seed(),r=projectMissionRequest(p.id,session),fetchImpl=vi.fn(()=>new Promise<Response>(()=>{})),pending=generateLearningPlanWithStatus(r,fetchImpl);await vi.advanceTimersByTimeAsync(25000);expect((await pending).source).toBe('fallback');expect(fetchImpl).toHaveBeenCalledTimes(1)})
})
it('History und Backup erhalten nur ID-Referenzen ohne automatische Projektänderung oder Vergütung',()=>{const p=seed(),plan=generateRuleBasedLearningPlan(projectMissionRequest(p.id,session));localStorage.setItem('mission.gamification.v1',JSON.stringify(initialGamificationState));const active={id:'session',startedAt:new Date().toISOString(),missionId:plan.id,goal:plan.goal,focusSeconds:60,plannedSeconds:1800,timeMode:'manual' as const,completedSteps:0,totalSteps:plan.steps.length,sourceProject:plan.sourceProject};const h=finishLearningSession([],normalizeActiveSession(active,[]),'completed',new Date().toISOString());expect(normalizeHistory(h)[0].sourceProject).toEqual(plan.sourceProject);localStorage.setItem('mission.saved-mission.v1',JSON.stringify({form:{goal:'Java',...session},mission:plan,remainingSeconds:1740,history:h,activeSession:null}));const before=localStorage.getItem(PROJECT_STORAGE_KEY);const b=parseBackup(exportBackup());replaceLocalData(b,true);expect(localStorage.getItem(PROJECT_STORAGE_KEY)).toBe(before);expect(JSON.parse(localStorage.getItem('mission.gamification.v1')!)).toEqual(initialGamificationState);expect((b.data['mission.saved-mission.v1'] as {mission:typeof plan}).mission.sourceProject).toEqual(plan.sourceProject)})

it('bewahrt gültige IDs aus Phase 11A mit Leerzeichen als technische Referenzen',()=>{const p=seed();p.id='bestehendes Projekt';p.roadmap.phases[0].id='bestehende Phase';p.roadmap.phases[0].milestones[0].id='bestehender Meilenstein';saveProject(p);const plan=generateRuleBasedLearningPlan(projectMissionRequest(p.id,session));expect(plan.sourceProject?.projectId).toBe(p.id);expect(plan.sourceProject?.phaseId).toBe(p.roadmap.phases[0].id)})
it('interpretiert ausdrücklich verneinte Kenntnisse nicht als bekannte Inhalte',()=>{const p=seed();p.startingLevel.priorKnowledge='Ich kenne keine Vererbung';saveProject(p);const r=projectMissionRequest(p.id,session);expect(r.projectContext?.phase.milestones[0].title).toBe('Vererbung');expect(unnecessaryKnownTopic([{title:'Vererbung lernen',kind:'learning',minutes:30}],r)).toBe(-1)})
