import { afterEach, expect, it, vi } from 'vitest'
import { handleProjectReviewRequest, REVIEW_MAX_TOKENS, reviewSystemPrompt } from './projectReviewApi.mjs'
import { localReview } from '../shared/projectReviewSchema.mjs'
const input={version:1,sessionId:'s',projectGoal:'Japanisch lernen',phase:{id:'p',title:'Grundlagen'},milestoneIds:['m'],steps:[{id:'step',title:'Lesen versuchen',description:'Einen kleinen Text lesen',done:true}],focusSeconds:300,completedSteps:1,totalSteps:1}
const options=fetchImpl=>({env:{AI_PROVIDER:'groq',GROQ_API_KEY:'server-only-test-secret',GROQ_MODEL:'test-model'},fetchImpl})
const response=draft=>({ok:true,json:async()=>({choices:[{message:{content:JSON.stringify(draft)}}]})})
afterEach(()=>{vi.useRealTimers();vi.restoreAllMocks()})
it('Mock ohne externe Anfrage und ohne automatische known-Aussage',async()=>{const fetchImpl=vi.fn();const result=await handleProjectReviewRequest(input,{env:{AI_PROVIDER:'mock'},fetchImpl});expect(result.status).toBe(200);expect(result.body.review.suggestedKnown).toEqual([]);expect(fetchImpl).not.toHaveBeenCalled()})
it('validiert kompakten Providervertrag und nutzt konservativen Prompt',async()=>{const fetchImpl=vi.fn().mockResolvedValue(response({...localReview(input),suggestedInProgress:['Lesen']}));const result=await handleProjectReviewRequest(input,options(fetchImpl));expect(result.status).toBe(200);const body=JSON.parse(fetchImpl.mock.calls[0][1].body);expect(body.max_tokens).toBe(REVIEW_MAX_TOKENS);expect(REVIEW_MAX_TOKENS).toBeLessThanOrEqual(1024);expect(body.messages[0].content).toContain('Erledigte Schritte beweisen keine Beherrschung');expect(JSON.stringify(body)).not.toMatch(/history|coins|prestige|orbs/i);expect(JSON.stringify(result)).not.toContain('server-only-test-secret');expect(reviewSystemPrompt).toContain('Nutzer bestätigt')})
it.each(['unknown-id','too-many','novel-known','bad-json'])('%s Providerantwort wird verworfen',async kind=>{let draft=localReview(input);if(kind==='unknown-id')draft.milestoneSuggestions[0].milestoneId='foreign';if(kind==='too-many')draft.suggestedWeak=['1','2','3','4'];if(kind==='novel-known')draft.suggestedKnown=['Lesen'];if(kind==='bad-json')draft={invalid:true};const result=await handleProjectReviewRequest(input,options(vi.fn().mockResolvedValue(response(draft))));expect(result.status).toBe(502)})
it('bereits bestätigtes known darf als Vorschlag erscheinen',async()=>{const request={...input,learningState:{version:1,known:['Hiragana'],inProgress:[],weak:[],recentProgress:[],nextSessionNote:''}};const result=await handleProjectReviewRequest(request,options(vi.fn().mockResolvedValue(response({...localReview(input),suggestedKnown:['Hiragana']}))));expect(result.status).toBe(200)})
it.each(['offline','429'])('%s sicher diagnostiziert ohne Retry oder Freitextlog',async kind=>{const log=vi.spyOn(console,'error').mockImplementation(()=>{});const fetchImpl=kind==='offline'?vi.fn().mockRejectedValue(new Error('private learner text')):vi.fn().mockResolvedValue({ok:false,status:429});const result=await handleProjectReviewRequest(input,options(fetchImpl));expect(result.status).toBe(502);expect(fetchImpl).toHaveBeenCalledTimes(1);expect(JSON.stringify(result)).not.toMatch(/private learner text|server-only-test-secret/);expect(JSON.stringify(log.mock.calls)).not.toContain(input.projectGoal)})
it('Timeout ohne Wiederholung',async()=>{vi.useFakeTimers();const fetchImpl=vi.fn().mockImplementation((_,init)=>new Promise((resolve,reject)=>init.signal.addEventListener('abort',()=>reject(new Error('abort')))));const promise=handleProjectReviewRequest(input,options(fetchImpl));await vi.advanceTimersByTimeAsync(20000);expect((await promise).status).toBe(502);expect(fetchImpl).toHaveBeenCalledTimes(1)})
it('zusätzliche History oder Belohnungsdaten werden vor Provider-Aufruf abgelehnt',async()=>{const fetchImpl=vi.fn();for(const data of [{history:[]},{coins:100},{prestige:1}])expect((await handleProjectReviewRequest({...input,...data},options(fetchImpl))).status).toBe(400);expect(fetchImpl).not.toHaveBeenCalled()})
