import { afterEach, describe, expect, it, vi } from 'vitest'
import { handleLearningPlanRequest, projectMissionPrompt } from './learningPlanApi.mjs'
import { buildProjectMissionContext } from '../shared/projectMissionContext.mjs'
import { diagnoseAiPlanDraft, validatePlanInput, validateLearningPlanResponse } from '../shared/learningPlanSchema.mjs'
const project={version:1,id:'project-java',title:'Java lernen',goal:'Java anwenden',createdAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z',status:'active',startingLevel:{type:'basic',priorKnowledge:'Vererbung'},duration:{type:'open-ended'},weeklyMinutes:120,daysPerWeek:3,learningContext:{materials:['none']},manualNotes:'PRIVATE_NOTES',roadmap:{version:1,summary:'Java Roadmap',phases:[{id:'phase-streams',title:'Streams',description:'Nächste Anwendung',order:0,milestones:[{id:'milestone-streams',title:'Streams anwenden',order:0}]}]}}
const input={goal:project.goal,timeBudgetMinutes:30,energyLevel:'low',learningBlocker:'starting',learningContext:project.learningContext,projectContext:buildProjectMissionContext(project)}
afterEach(()=>vi.restoreAllMocks())
describe('Projektmission nutzt normalen Planvertrag',()=>{
 it.each([5,30,60])('Mock erzeugt %i Minuten mit normalem Lernplan und sourceProject',async timeBudgetMinutes=>{const request={...input,timeBudgetMinutes},fetchImpl=vi.fn();const result=await handleLearningPlanRequest(request,{env:{AI_PROVIDER:'mock'},fetchImpl});expect(result.status).toBe(200);expect(validateLearningPlanResponse(result.body,request)).toBe(true);expect(result.body.plan.sourceProject).toEqual({projectId:project.id,phaseId:'phase-streams',milestoneIds:['milestone-streams']});expect(result.body.clarifyingQuestion).toBeNull();expect(fetchImpl).not.toHaveBeenCalled()})
 it('Groq erhält nur kompakte Projekt- und Sessionangaben ohne History, Coins oder Notizen',async()=>{const draft={clarifyingQuestion:null,steps:[{title:'Streams anwenden',description:'Versuche einen eigenen kleinen Java-Stream und notiere eine offene Frage.',kind:'practice',minutes:30,topicFocus:'Streams'}]};const fetchImpl=vi.fn().mockResolvedValue(new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify(draft)}}]})));const result=await handleLearningPlanRequest(input,{env:{AI_PROVIDER:'groq',GROQ_API_KEY:'test-placeholder',GROQ_MODEL:'test-model'},fetchImpl});expect(result.status).toBe(200);const body=JSON.parse(fetchImpl.mock.calls[0][1].body),user=JSON.parse(body.messages[1].content);expect(user.projectContext).toEqual(input.projectContext);expect(body.max_tokens).toBe(2048);expect(body.messages[0].content).toContain(projectMissionPrompt);expect(JSON.stringify(user)).not.toMatch(/PRIVATE_NOTES|history|coins|prestige|orb/);expect(fetchImpl).toHaveBeenCalledTimes(1)})
 it('Vorwissenprüfung verwirft erneutes Hauptlernen, erlaubt kurze markierte Wiederholung',()=>{const next={title:'Streams anwenden',description:'Versuche einen kleinen Java-Stream.',kind:'practice',minutes:27,topicFocus:'Streams'};const repeat={title:'Wiederholung Vererbung',description:'Rufe den bekannten Zusammenhang kurz ab.',kind:'learning',minutes:3,topicFocus:'Java'};expect(diagnoseAiPlanDraft({clarifyingQuestion:null,steps:[repeat,next]},input)).toBeNull();expect(diagnoseAiPlanDraft({clarifyingQuestion:null,steps:[{...repeat,title:'Vererbung lernen'},next]},input)).toBe('known_topic_replanned')})
 it('falsche Referenz, extra Freitext und neue Rückfragen werden abgelehnt',async()=>{const result=await handleLearningPlanRequest(input,{env:{AI_PROVIDER:'mock'}});expect(validateLearningPlanResponse({...result.body,plan:{...result.body.plan,sourceProject:{projectId:'wrong'}}},input)).toBe(false);expect(validatePlanInput({...input,projectContext:{...input.projectContext,coins:100}})).toBe(false);expect(validateLearningPlanResponse({...result.body,clarifyingQuestion:'Welches Thema?'},input)).toBe(false)})
 it('Diagnosen enthalten keine Projekt-Freitexte, keinen Providerinhalt oder Schlüssel',async()=>{const log=vi.spyOn(console,'warn').mockImplementation(()=>{}),fetchImpl=vi.fn().mockResolvedValue(new Response(JSON.stringify({choices:[{message:{content:'PRIVATE_PROVIDER_TEXT'}}]})));const request={...input,projectContext:{...input.projectContext,startingLevel:{type:'custom',description:'PRIVATE_KNOWLEDGE'}}};const result=await handleLearningPlanRequest(request,{env:{AI_PROVIDER:'groq',GROQ_API_KEY:'test-placeholder',GROQ_MODEL:'test-model'},fetchImpl});expect(result.status).toBe(502);expect(JSON.stringify(result)+JSON.stringify(log.mock.calls)).not.toMatch(/PRIVATE|test-placeholder/);expect(fetchImpl).toHaveBeenCalledTimes(1)})
})
