import { describe, it, expect, vi, afterEach } from 'vitest'
import { handleProjectRoadmapRequest, roadmapSystemPrompt, ROADMAP_MAX_TOKENS } from './projectRoadmapApi.mjs'
import { readRoadmap, createFallbackRoadmap } from '../shared/longTermProjectSchema.mjs'
const input={title:'Japanisch',goal:'PRIVATE_PROJECT_GOAL',startingLevel:{type:'custom',description:'PRIVATE_START'},duration:{type:'fixed-days',days:300},weeklyMinutes:120,daysPerWeek:3,learningContext:{materials:['other'],materialsDetails:'PRIVATE_MATERIAL'}}
afterEach(()=>vi.restoreAllMocks())
describe('Roadmap-API',()=>{
 it('Mock bleibt kostenfrei und kompakt',async()=>{const fetchImpl=vi.fn();const result=await handleProjectRoadmapRequest(input,{env:{AI_PROVIDER:'mock'},fetchImpl});expect(result.status).toBe(200);expect(readRoadmap(result.body.roadmap).phases.length).toBeLessThanOrEqual(8);expect(fetchImpl).not.toHaveBeenCalled()})
 it('Groq-Adapter erhält alle Felder und begrenzten Output',async()=>{let n=0;const draft=createFallbackRoadmap(input,()=>String(n++));const fetchImpl=vi.fn().mockResolvedValue(new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify(draft)}}]})));const result=await handleProjectRoadmapRequest(input,{env:{AI_PROVIDER:'groq',GROQ_API_KEY:'test-placeholder',GROQ_MODEL:'test-model'},fetchImpl});expect(result.status).toBe(200);expect(fetchImpl).toHaveBeenCalledTimes(1);const body=JSON.parse(fetchImpl.mock.calls[0][1].body);expect(body.max_tokens).toBe(ROADMAP_MAX_TOKENS);expect(JSON.parse(body.messages[1].content)).toEqual(input);expect(body.messages[0].content).toBe(roadmapSystemPrompt);expect(roadmapSystemPrompt).toMatch(/Keine Tageslisten/);expect(roadmapSystemPrompt).toMatch(/keine Materialien erfinden/);expect(roadmapSystemPrompt).toMatch(/100%/)})
 it('beschädigte oder abgeschnittene AI-Antwort wird ohne Retry und ohne Freitextlogs verworfen',async()=>{const log=vi.spyOn(console,'warn').mockImplementation(()=>{});for(const content of ['PRIVATE_BAD_RESPONSE','{}',JSON.stringify({version:1,summary:'PRIVATE_SECRET',phases:[]})]) {const fetchImpl=vi.fn().mockResolvedValue(new Response(JSON.stringify({choices:[{message:{content},finish_reason:'stop'}]})));const result=await handleProjectRoadmapRequest(input,{env:{AI_PROVIDER:'groq',GROQ_API_KEY:'test-placeholder',GROQ_MODEL:'test-model'},fetchImpl});expect(result.status).toBe(502);expect(fetchImpl).toHaveBeenCalledTimes(1);expect(JSON.stringify(result)).not.toContain('PRIVATE');}expect(JSON.stringify(log.mock.calls)).not.toMatch(/PRIVATE|test-placeholder/);})
 it('validiert Eingaben vor Provider-Aufruf',async()=>{vi.spyOn(console,'warn').mockImplementation(()=>{});const fetchImpl=vi.fn();expect((await handleProjectRoadmapRequest({...input,weeklyMinutes:0},{fetchImpl})).status).toBe(400);expect(fetchImpl).not.toHaveBeenCalled()})
 it('nicht konfigurierter Provider liefert sichere Diagnose',async()=>{vi.spyOn(console,'warn').mockImplementation(()=>{});const result=await handleProjectRoadmapRequest(input,{env:{AI_PROVIDER:'groq'}});expect(result.status).toBe(503);expect(JSON.stringify(result)).not.toContain('PRIVATE')})
})

it('begrenzt Provider-Bytes vor dem JSON-Parsing',async()=>{vi.spyOn(console,'warn').mockImplementation(()=>{});const fetchImpl=vi.fn().mockResolvedValue(new Response('x'.repeat(65537)));const result=await handleProjectRoadmapRequest(input,{env:{AI_PROVIDER:'groq',GROQ_API_KEY:'test-placeholder',GROQ_MODEL:'test-model'},fetchImpl});expect(result.status).toBe(502);expect(result.body.error.category).toBe('model_output_truncated');expect(fetchImpl).toHaveBeenCalledTimes(1)})
it('verwendet die vorhandene Materialprüfung für Roadmap-Aktionen',async()=>{vi.spyOn(console,'warn').mockImplementation(()=>{});let n=0;const draft=createFallbackRoadmap(input,()=>String(n++));draft.phases[0].description='Öffne das Skript und lies die erste Seite.';const fetchImpl=vi.fn().mockResolvedValue(new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(draft)}}]})));const result=await handleProjectRoadmapRequest(input,{env:{AI_PROVIDER:'groq',GROQ_API_KEY:'test-placeholder',GROQ_MODEL:'test-model'},fetchImpl});expect(result.status).toBe(502);expect(result.body.error.category).toBe('invalid_plan_schema')})
