import { useEffect, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import { localReview, readReviewProposal, type ReviewProposal } from '../../shared/projectReviewSchema.mjs'
import { generateSessionReview, type ReviewTicket } from '../services/projectReview'
export default function ProjectReviewDialog({ticket,initial,enabled,onDraft,onApply,onSkip}:{ticket:ReviewTicket;initial?:ReviewProposal;enabled:boolean;onDraft:(draft:ReviewProposal)=>void;onApply:(draft:ReviewProposal)=>void;onSkip:()=>void}) {
 const [draft,setDraft]=useState(()=>initial ?? localReview(ticket.input)),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 const panel=useRef<HTMLElement>(null),close=useRef(onSkip);close.current=onSkip
 const alive=useRef(true),draftRevision=useRef(0)
 useEffect(()=>{alive.current=true;const previous=document.activeElement as HTMLElement|null;const old=Array.from(document.body.children).filter(e=>!e.contains(panel.current)).map(e=>({e:e as HTMLElement,inert:(e as HTMLElement).inert,hidden:e.getAttribute('aria-hidden')}));old.forEach(({e})=>{e.inert=true;e.setAttribute('aria-hidden','true')});const overflow=document.body.style.overflow;document.body.style.overflow='hidden';const controls=()=>Array.from(panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),textarea:not(:disabled)') ?? []);controls()[0]?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();close.current()}if(e.key==='Tab'){const list=controls();if(e.shiftKey&&document.activeElement===list[0]){e.preventDefault();list.at(-1)?.focus()}else if(!e.shiftKey&&document.activeElement===list.at(-1)){e.preventDefault();list[0]?.focus()}}};const focus=(e:FocusEvent)=>{if(e.target instanceof Node&&!panel.current?.contains(e.target))controls()[0]?.focus()};document.addEventListener('keydown',key);document.addEventListener('focusin',focus);return()=>{alive.current=false;document.removeEventListener('keydown',key);document.removeEventListener('focusin',focus);document.body.style.overflow=overflow;old.forEach(({e,inert,hidden})=>{e.inert=inert;if(hidden===null)e.removeAttribute('aria-hidden');else e.setAttribute('aria-hidden',hidden)});if(previous?.isConnected)previous.focus()}},[])
 function change(next:ReviewProposal){draftRevision.current++;setDraft(next);if(!enabled)return;let valid:ReviewProposal;try{valid=readReviewProposal(next,ticket.input.milestoneIds)}catch{return}try{onDraft(valid)}catch{setNotice('Der Entwurf konnte nicht gespeichert werden. Er bleibt in diesem Dialog erhalten.')}}
 async function ai(){const revision=draftRevision.current;setBusy(true);const result=await generateSessionReview(ticket.input);if(alive.current){if(revision===draftRevision.current){change(result.proposal);setNotice(result.notice)}else setNotice('Dein inzwischen bearbeiteter Entwurf wurde beibehalten.');setBusy(false)}}
 return createPortal(<div className="shop-modal-backdrop collection-backdrop"><section ref={panel} className="shop-confirm-modal collection-dialog project-review-dialog" role="dialog" aria-modal="true" aria-labelledby="project-review-title"><h2 id="project-review-title">Projektfortschritt übernehmen</h2><p>Vorschlag aus dieser Session. Erledigte Schritte sind kein Nachweis, dass du ein Thema beherrschst. Erst deine Bestätigung verändert das Projekt.</p>{ticket.input.steps.length<ticket.input.totalSteps&&<p className="field-hint">Begrenzter Ausschnitt: {ticket.input.steps.length} von {ticket.input.totalSteps} Schritten.</p>}{!enabled&&<p role="status">Übernehmen ist nur im schreibenden Tab bei angehaltenem Timer möglich.</p>}{notice&&<p role="status">{notice}</p>}
 {editing?<><label>Session-Zusammenfassung<textarea maxLength={240} value={draft.sessionSummary} onChange={e=>change({...draft,sessionSummary:e.target.value})}/></label>{([['suggestedKnown','Bekannt'],['suggestedInProgress','In Arbeit'],['suggestedWeak','Unsicher']] as const).map(([key,label])=><fieldset key={key}><legend>{label}</legend>{draft[key].map((text,index)=><div key={index}><input aria-label={label+' '+(index+1)} maxLength={120} value={text} onChange={e=>change({...draft,[key]:draft[key].map((v,i)=>i===index?e.target.value:v)})}/><button type="button" aria-label={label+' entfernen '+(index+1)} onClick={()=>change({...draft,[key]:draft[key].filter((_,i)=>i!==index)})}>Entfernen</button></div>)}<button type="button" disabled={draft[key].length>=3} onClick={()=>change({...draft,[key]:[...draft[key],'']})}>{label} hinzufügen</button></fieldset>)}<label>Notiz für die nächste Session<textarea maxLength={240} value={draft.nextSessionNote} onChange={e=>change({...draft,nextSessionNote:e.target.value})}/></label></>:<><p>{draft.sessionSummary}</p>{([['suggestedKnown','Bekannt'],['suggestedInProgress','In Arbeit'],['suggestedWeak','Unsicher']] as const).map(([key,label])=><p key={key}><strong>{label}: </strong>{draft[key].join(' · ')||'Keine Aussage – bei Bedarf selbst ergänzen.'}</p>)}{draft.nextSessionNote&&<p>{draft.nextSessionNote}</p>}</>}
 {draft.milestoneSuggestions.map((m,i)=><label key={m.milestoneId}><input type="checkbox" checked={m.suggestion==='mark-completed'} onChange={e=>change({...draft,milestoneSuggestions:draft.milestoneSuggestions.map((v,j)=>j===i?{...v,suggestion:e.target.checked?'mark-completed':'keep-open'}:v)})}/>Meilenstein als erledigt bestätigen: {ticket.milestoneTitles[m.milestoneId] ?? m.milestoneId}<span className="field-hint">{m.reason}</span></label>)}
 <div className="project-actions"><button type="button" disabled={!enabled||busy} onClick={()=>{try{onApply(readReviewProposal(draft,ticket.input.milestoneIds))}catch(e){setNotice(e instanceof Error?e.message:'Übernahme nicht möglich.')}}}>Übernehmen</button><button type="button" onClick={()=>setEditing(v=>!v)}>{editing?'Vorschau':'Bearbeiten'}</button><button type="button" onClick={onSkip}>Überspringen</button><button type="button" disabled={busy} onClick={()=>void ai()}>{busy?'Vorschlag wird erstellt …':'KI-Vorschlag erstellen'}</button></div></section></div>,document.body)
}
