import { screen, within } from './services/testNavigation'
// @vitest-environment jsdom
import { act, cleanup, fireEvent, render } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import App from './App'
import { createTestLocks } from './services/testLocks'
import { MOBILE_QUERY } from './services/useMobileLayout'
import { createProject, projectId, saveProject, loadProjects } from './services/longTermProjects'
import { createFallbackRoadmap, PROJECT_STORAGE_KEY, type ProjectInput } from '../shared/longTermProjectSchema.mjs'
import { GAMIFICATION_STORAGE_KEY } from './services/gamification'
const key='mission.saved-mission.v1',stored=()=>JSON.parse(localStorage.getItem(key)!),game=()=>JSON.parse(localStorage.getItem(GAMIFICATION_STORAGE_KEY)!)
const input:ProjectInput={title:'Japanisch lernen',goal:'Japanisch im Alltag verwenden',startingLevel:{type:'basic',priorKnowledge:'Hiragana'},duration:{type:'open-ended'},weeklyMinutes:120,daysPerWeek:3,learningContext:{materials:['none']}}
let now=0
const click=(name:string|RegExp)=>fireEvent.click(screen.getByRole('button',{name}))
function tick(ms:number){act(()=>{now+=ms;vi.advanceTimersByTime(250)})}
function seed(){const p=createProject(input,createFallbackRoadmap(input,projectId));saveProject(p);return p}
async function daily(p:ReturnType<typeof seed>,minutes='5',strategy='free') {
 click(p.title+' · Aktiv');click('Heutige Mission erstellen');fireEvent.change(screen.getByLabelText('Heute verfügbare Zeit'),{target:{value:minutes}});fireEvent.change(screen.getByLabelText('Energielevel'),{target:{value:'low'}});fireEvent.change(screen.getByLabelText('Lernblocker'),{target:{value:'starting'}})
 if(strategy!=='free'){fireEvent.click(screen.getByText('Fokusstrategie (optional)'));fireEvent.change(screen.getByLabelText('Fokusstrategie'),{target:{value:strategy}})}
 await act(async()=>{click('Tagesmission erstellen')})
}
beforeEach(()=>{localStorage.clear();now=0;vi.useFakeTimers();vi.spyOn(performance,'now').mockImplementation(()=>now);Object.defineProperty(navigator,'locks',{configurable:true,value:createTestLocks()});vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new TypeError('offline')));localStorage.setItem('mission.onboarding.v1',JSON.stringify({version:1,status:'dismissed'}))})
afterEach(()=>{cleanup();vi.useRealTimers();vi.restoreAllMocks();vi.unstubAllGlobals()})
it('Projektmission nutzt normalen Timer, Fokusmodus, Coins, History und Reload ohne Projekt-Rückschreibung',async()=>{
 const p=seed(),first=render(<App/>),beforeProject=localStorage.getItem(PROJECT_STORAGE_KEY),beforeGame=localStorage.getItem(GAMIFICATION_STORAGE_KEY)
 await daily(p);expect(stored().mission.sourceProject.projectId).toBe(p.id);expect(stored().mission.timeBudgetMinutes).toBe(5);expect(stored().mission.energyLevel).toBe('low');expect(localStorage.getItem(GAMIFICATION_STORAGE_KEY)).toBe(beforeGame);expect(screen.getByText('Projekt: Japanisch lernen')).toBeTruthy();const planId=stored().mission.id
 click(/Start/);expect(screen.getByRole('main',{name:'Fokusmodus'})).toBeTruthy();expect(stored().activeSession.sourceProject.projectId).toBe(p.id);tick(60_000);expect(game().coins).toBe(1);expect(game().totalFocusMilliseconds).toBe(60_000);click('Fokusmodus verlassen');first.unmount();render(<App/>);expect(stored().mission.id).toBe(planId);expect(stored().activeSession.sourceProject.projectId).toBe(p.id);click(/Start/);tick(240_000);expect(stored().history[0]).toMatchObject({focusSeconds:300,status:'completed',sourceProject:{projectId:p.id}});expect(game().coins).toBe(5);expect(localStorage.getItem(PROJECT_STORAGE_KEY)).toBe(beforeProject)
})
it('Planeditor erhält Projekt- und Step-IDs und erlaubt Zeit- und Fokusstrategieänderungen',async()=>{const p=seed();render(<App/>);await daily(p);const plan=stored().mission;click('Lernplan bearbeiten');fireEvent.change(screen.getByLabelText('Gesamtdauer in Minuten'),{target:{value:'10'}});fireEvent.click(screen.getByRole('button',{name:/Schritt 1 bearbeiten:/}));fireEvent.change(screen.getByLabelText('Titel'),{target:{value:'Mein Einstieg'}});fireEvent.change(screen.getByLabelText('Fokusstrategie'),{target:{value:'pomodoro'}});click('Änderungen speichern');expect(stored().mission.id).toBe(plan.id);expect(stored().mission.steps[0]).toMatchObject({id:plan.steps[0].id,title:'Mein Einstieg'});expect(stored().mission.focusStrategy.mode).toBe('pomodoro');expect(stored().mission.sourceProject).toEqual(plan.sourceProject);expect(stored().remainingSeconds).toBe(600);expect(game().coins).toBe(0)})
it('Pomodoro zählt bei Projektmissionen nur Fokuszeit und wartet nach Pausen',async()=>{const p=seed();render(<App/>);await daily(p,'30','pomodoro');click(/Start/);tick(25*60_000);expect(game().totalFocusMilliseconds).toBe(25*60_000);expect(stored().focusBlocks.phase).toBe('break');click('Pause starten');tick(5*60_000);expect(game().coins).toBe(25);expect(game().totalFocusMilliseconds).toBe(25*60_000);click('Fokusblock starten');tick(5*60_000);expect(stored().history[0]).toMatchObject({focusSeconds:1800,sourceProject:{projectId:p.id}});expect(game().coins).toBe(30)})
it('manuelles Meilensteinhäkchen vergütet nichts und die nächste offene Phase wird verwendet',async()=>{const p=seed();render(<App/>);click(p.title+' · Aktiv');const before=localStorage.getItem(GAMIFICATION_STORAGE_KEY);const first=p.roadmap.phases[0].milestones[0];fireEvent.click(screen.getByRole('checkbox',{name:'Meilenstein erledigt: '+first.title}));expect(loadProjects().projects[0].roadmap.phases[0].milestones[0].status).toBe('completed');expect(localStorage.getItem(GAMIFICATION_STORAGE_KEY)).toBe(before);await daily(p);expect(stored().mission.sourceProject.phaseId).toBe(p.roadmap.phases[1].id)})
it.each(['paused','completed','archived'] as const)('%s bietet keine Tagesmission an',status=>{const p=seed();saveProject({...p,status});render(<App/>);click(p.title+' · '+({paused:'Pausiert',completed:'Abgeschlossen',archived:'Archiviert'}[status]));expect(screen.queryByRole('button',{name:'Heutige Mission erstellen'})).toBeNull()})
it('Löschung während Anfrage ersetzt den bestehenden Plan nicht; bereits übernommene Mission bleibt nach Löschung nutzbar',async()=>{const p=seed();render(<App/>);await daily(p);const plan=stored().mission;let resolve:(r:Response)=>void=()=>{};vi.stubGlobal('fetch',vi.fn(()=>new Promise<Response>(r=>{resolve=r})));click(p.title+' · Aktiv');click('Heutige Mission erstellen');act(()=>{click('Tagesmission erstellen')});localStorage.removeItem(PROJECT_STORAGE_KEY);await act(async()=>{resolve(new Response('{}'))});expect(screen.getByRole('alert').textContent).toMatch(/nicht mehr vorhanden/);expect(stored().mission.id).toBe(plan.id);click('Abbrechen');click(/Start/);tick(60_000);expect(game().totalFocusMilliseconds).toBe(60_000);expect(stored().activeSession.sourceProject.projectId).toBe(p.id)})
it('neue Tagesmission hat neue Plan-IDs und schließt eine pausierte echte Session mit Herkunft sauber ab',async()=>{const p=seed();render(<App/>);await daily(p);const first=stored().mission.id;click(/Start/);tick(60_000);click('Fokusmodus verlassen');vi.stubGlobal('confirm',vi.fn(()=>true));await daily(p);expect(stored().mission.id).not.toBe(first);expect(stored().history[0]).toMatchObject({status:'ended_early',focusSeconds:60,sourceProject:{projectId:p.id}});expect(stored().activeSession).toBeNull();expect(game().coins).toBe(1)})
it('mobile Bibliothek führt zum normalen Plan ohne neue Navigation oder großes Projektformular',async()=>{vi.stubGlobal('innerWidth',390);vi.stubGlobal('matchMedia',vi.fn((q:string)=>({matches:q===MOBILE_QUERY,media:q,addEventListener:vi.fn(),removeEventListener:vi.fn()})));const p=seed();render(<App/>);const nav=within(screen.getByRole('navigation',{name:'Mobile Hauptnavigation'}));fireEvent.click(nav.getByRole('button',{name:'Projekte'}));click(p.title+' · Aktiv');click('Heutige Mission erstellen');expect(screen.queryByLabelText('Projekttitel')).toBeNull();expect(screen.queryByLabelText('Vorwissen')).toBeNull();await act(async()=>click('Tagesmission erstellen'));expect(nav.getByRole('button',{name:'Plan'}).getAttribute('aria-current')).toBe('page');expect(screen.getByText('Projekt: Japanisch lernen')).toBeTruthy();expect(nav.getAllByRole('button')).toHaveLength(6)})
