import { screen, within } from './services/testNavigation'
// @vitest-environment jsdom
import { act, cleanup, fireEvent, render } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import App from './App'
import { createTestLocks } from './services/testLocks'
import { MOBILE_QUERY } from './services/useMobileLayout'
import { createProject, projectId, saveProject, loadProjects } from './services/longTermProjects'
import { createFallbackRoadmap, PROJECT_STORAGE_KEY, type ProjectInput } from '../shared/longTermProjectSchema.mjs'
import { GAMIFICATION_STORAGE_KEY } from './services/gamification'
const key='mission.saved-mission.v1',stored=()=>JSON.parse(localStorage.getItem(key)!),game=()=>localStorage.getItem(GAMIFICATION_STORAGE_KEY)
const input:ProjectInput={title:'Japanisch lernen',goal:'Japanisch im Alltag verwenden',startingLevel:{type:'basic',priorKnowledge:'Hiragana'},duration:{type:'open-ended'},weeklyMinutes:120,daysPerWeek:3,learningContext:{materials:['none']}}
let now=0
const click=(name:string|RegExp)=>fireEvent.click(screen.getByRole('button',{name}))
function tick(ms:number){act(()=>{now+=ms;vi.advanceTimersByTime(250)})}
function seed(){const p=createProject(input,createFallbackRoadmap(input,projectId));saveProject(p);return p}
it('zeigt Review-Loading ohne Doppelanfrage und beendet es beim vorhandenen Fallback', async () => {
 const p=seed();render(<App/>);await finish(p);click('Projektfortschritt übernehmen')
 const beforeProject=localStorage.getItem(PROJECT_STORAGE_KEY), beforeGame=game()
 let reject!:(e:Error)=>void;const request=vi.fn(()=>new Promise<Response>((_,r)=>{reject=r}));vi.stubGlobal('fetch',request)
 click('KI-Vorschlag erstellen');expect(screen.getByText('Fortschritt wird ausgewertet …')).toBeTruthy()
 const button=screen.getByRole('button',{name:/Vorschlag wird erstellt/}) as HTMLButtonElement
 expect(button.disabled).toBe(true);fireEvent.click(button);expect(request).toHaveBeenCalledOnce()
 await act(async()=>reject(new TypeError('offline')))
 expect(screen.queryByText('Fortschritt wird ausgewertet …')).toBeNull();expect(screen.getByRole('button',{name:'KI-Vorschlag erstellen'})).toBeTruthy()
 expect(localStorage.getItem(PROJECT_STORAGE_KEY)).toBe(beforeProject);expect(game()).toBe(beforeGame)
})
async function finish(p:ReturnType<typeof seed>,early=false){click(p.title+' · Aktiv');click('Heutige Mission erstellen');fireEvent.change(screen.getByLabelText('Heute verfügbare Zeit'),{target:{value:'5'}});await act(async()=>click('Tagesmission erstellen'));if(document.querySelector('.mobile-navigation'))click('Fokusmodus öffnen');click(/Start|Fortsetzen/);tick(early?60_000:300_000);if(early)click('Session beenden')}
beforeEach(()=>{localStorage.clear();now=0;vi.useFakeTimers();vi.spyOn(performance,'now').mockImplementation(()=>now);Object.defineProperty(navigator,'locks',{configurable:true,value:createTestLocks()});vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new TypeError('offline')));localStorage.setItem('mission.onboarding.v1',JSON.stringify({version:1,status:'dismissed'}))})
afterEach(()=>{cleanup();vi.useRealTimers();vi.restoreAllMocks();vi.unstubAllGlobals()})
it('Projektabschluss bietet Review; Bearbeiten und Bestätigen erzeugen keine weiteren Rewards',async()=>{const p=seed();render(<App/>);await finish(p);expect(stored().history[0].projectReview.status).toBe('pending');expect(loadProjects().projects[0].learningState).toBeUndefined();const reward=game();click('Projektfortschritt übernehmen');const dialog=screen.getByRole('dialog',{name:'Projektfortschritt übernehmen'});expect(dialog.getAttribute('aria-modal')).toBe('true');click('Bearbeiten');fireEvent.change(screen.getByLabelText('Session-Zusammenfassung'),{target:{value:'Kleine Sätze geübt'}});for(const [label,value] of [['Bekannt','Hiragana'],['In Arbeit','Sätze'],['Unsicher','Partikel']]){click(label+' hinzufügen');fireEvent.change(screen.getByLabelText(label+' 1'),{target:{value}})}fireEvent.change(screen.getByLabelText('Notiz für die nächste Session'),{target:{value:'Partikel üben'}});const checkbox=within(dialog).getByRole('checkbox');fireEvent.click(checkbox);expect(loadProjects().projects[0].roadmap.phases[0].milestones[0].status).not.toBe('completed');click('Übernehmen');expect(screen.queryByRole('dialog')).toBeNull();expect(loadProjects().projects[0].learningState).toMatchObject({known:['Hiragana'],inProgress:['Sätze'],weak:['Partikel'],nextSessionNote:'Partikel üben'});expect(stored().history[0].projectReview.status).toBe('applied');expect(loadProjects().projects[0].roadmap.phases[0].milestones[0].status).toBe('completed');expect(game()).toBe(reward);expect(screen.queryByRole('button',{name:'Projektfortschritt übernehmen'})).toBeNull()})
it('Review überspringen und Reload vor Apply erhalten Entwurf und stabile sourceProject',async()=>{const p=seed(),first=render(<App/>);await finish(p);click('Projektfortschritt übernehmen');click('Bearbeiten');fireEvent.change(screen.getByLabelText('Session-Zusammenfassung'),{target:{value:'Mein Entwurf'}});click('Überspringen');expect(stored().history[0].projectReview.status).toBe('skipped');const source=stored().history[0].sourceProject;first.unmount();render(<App/>);fireEvent.click(screen.getByText('Deine letzten Missionen'));click('Projekt-Review erneut öffnen');expect(screen.getByText('Mein Entwurf')).toBeTruthy();click('Übernehmen');expect(stored().history[0].sourceProject).toEqual(source);cleanup();render(<App/>);expect(screen.queryByRole('button',{name:'Projektfortschritt übernehmen'})).toBeNull()})
it('normaler Sessionabschluss bietet keinen Projekt-Review',async()=>{render(<App/>);click('Plan');fireEvent.change(screen.getByLabelText('Was möchtest du lernen?'),{target:{value:'Java lernen'}});await act(async()=>click(/Mission planen/));click(/Start/);tick(60_000);click('Session beenden');expect(screen.queryByRole('button',{name:'Projektfortschritt übernehmen'})).toBeNull()})
it.each(['deleted','archived','phase','milestone'])('%s während Review verhindert Apply',async kind=>{const p=seed();render(<App/>);await finish(p);click('Projektfortschritt übernehmen');if(kind==='deleted')localStorage.removeItem(PROJECT_STORAGE_KEY);else if(kind==='archived')saveProject({...p,status:'archived'});else {const changed=structuredClone(p);if(kind==='phase')changed.roadmap.phases[0].title='Geändert';else changed.roadmap.phases[0].milestones[0].id=projectId();saveProject(changed)}click('Übernehmen');expect(screen.getByRole('dialog')).toBeTruthy();expect(stored().history[0].projectReview.status).toBe('pending');click('Überspringen')})
it('gelöschtes Projekt zeigt nach Reload keinen Review; History bleibt',async()=>{const p=seed(),first=render(<App/>);await finish(p);localStorage.removeItem(PROJECT_STORAGE_KEY);first.unmount();render(<App/>);expect(stored().history[0].sourceProject.projectId).toBe(p.id);expect(screen.queryByRole('button',{name:'Projektfortschritt übernehmen'})).toBeNull()})
it('KI-Fallback ist editierbar und speichert keine Kenntnisse automatisch',async()=>{const p=seed();render(<App/>);await finish(p);click('Projektfortschritt übernehmen');await act(async()=>click('KI-Vorschlag erstellen'));expect(screen.getByText(/Die KI-Auswertung war nicht verfügbar/)).toBeTruthy();expect(loadProjects().projects[0].learningState).toBeUndefined();click('Bearbeiten');click('Bekannt hinzufügen');fireEvent.change(screen.getByLabelText('Bekannt 1'),{target:{value:'Test'}});click('Bekannt entfernen 1');expect(screen.queryByLabelText('Bekannt 1')).toBeNull();click('Übernehmen');expect(loadProjects().projects[0].learningState?.known).toEqual([])})
it('bewusstes vorzeitiges Ende bietet Review',async()=>{const p=seed();render(<App/>);await finish(p,true);expect(stored().history[0].status).toBe('ended_early');expect(screen.getByRole('button',{name:'Projektfortschritt übernehmen'})).toBeTruthy()})
it('mobiler Review bleibt erreichbar ohne zusätzliche Navigation',async()=>{vi.stubGlobal('innerWidth',390);vi.stubGlobal('matchMedia',vi.fn((q:string)=>({matches:q===MOBILE_QUERY,media:q,addEventListener:vi.fn(),removeEventListener:vi.fn()})));const p=seed();render(<App/>);const nav=within(screen.getByRole('navigation',{name:'Mobile Hauptnavigation'}));fireEvent.click(nav.getByRole('button',{name:'Projekte'}));await finish(p);click('Projektfortschritt übernehmen');expect(screen.getByRole('dialog').className).toContain('project-review-dialog');click('Bearbeiten');expect(screen.getByLabelText('Session-Zusammenfassung').getAttribute('maxlength')).toBe('240');click('Überspringen');expect(screen.queryByRole('dialog')).toBeNull()})

it('Review bleibt ohne Writer-Lock sichtbar, Apply ist gesperrt',async()=>{const p=seed(),first=render(<App/>);await finish(p);first.unmount();Object.defineProperty(navigator,'locks',{configurable:true,value:{request:()=>new Promise(()=>{})}});render(<App/>);click('Projektfortschritt übernehmen');expect(screen.getByRole('button',{name:'Übernehmen'}).hasAttribute('disabled')).toBe(true);expect(screen.getByText(/schreibenden Tab bei angehaltenem Timer/)).toBeTruthy();click('Überspringen');expect(loadProjects().projects[0].learningState).toBeUndefined()})
it('späte KI-Antwort überschreibt keine inzwischen bearbeiteten Angaben',async()=>{const p=seed();render(<App/>);await finish(p);click('Projektfortschritt übernehmen');let resolve:(r:Response)=>void=()=>{};vi.stubGlobal('fetch',vi.fn(()=>new Promise<Response>(r=>{resolve=r})));act(()=>click('KI-Vorschlag erstellen'));click('Bearbeiten');fireEvent.change(screen.getByLabelText('Session-Zusammenfassung'),{target:{value:'Meine eigene Zusammenfassung'}});await act(async()=>resolve(new Response('{}')));expect(screen.getByLabelText('Session-Zusammenfassung').getAttribute('maxlength')).toBe('240');expect((screen.getByLabelText('Session-Zusammenfassung') as HTMLTextAreaElement).value).toBe('Meine eigene Zusammenfassung');expect(screen.getByText(/inzwischen bearbeiteter Entwurf/)).toBeTruthy()})
